language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
  - pip install git+https://github.com/marrow/marrow.util.git
  - pip install -e . --use-mirrors
script: ./setup.py --quiet nosetests
notifications:
  irc:
    channels: "irc.freenode.org#webcore"
    on_success: change
    on_failure: change
